CXX=pgc++
CXXFLAGS=-acc -Mcudalib=cusolver,cublas,cusparse -Mcuda -mp -ta=tesla -Minfo=accel
CXXFLAGS+=-fast -std=c++11 
CXXFLAGS+=-DUSE_GPU
LIBS=-I ../include -I ../include/common -L ../lib/ -lmonolish_gpu
MONOLISH=$(HOME)/Work/monolish/lib/# gomi!!

OBJS=gpu.out

all:$(OBJS)

gpu.out: gpu.cpp
	$(CXX) $(CXXFLAGS) $(LIBS) $^ -o $@
	export LD_LIBRARY_PATH=$(MONOLISH):$(LD_LIBRARY_PATH); ./$@
	
