#!/bin/bash
echo "// Tshi code is generated by gen_dense_diag_add.sh
#include \"../../../../include/monolish_blas.hpp\"
#include \"../../../internal/monolish_internal.hpp\"
#include \"tensor_dense_diag_op.hpp\"

namespace monolish {
"

# add scalar
for prec in double float; do
  for arg1 in tensor::tensor_Dense\<$prec\> view_tensor_Dense\<vector\<$prec\>,$prec\> view_tensor_Dense\<matrix::Dense\<$prec\>,$prec\> view_tensor_Dense\<tensor::tensor_Dense\<$prec\>,$prec\>; do
    echo "template <> void monolish::$arg1::diag_add(const $prec alpha) { tensor_Dense_diag_add_core(*this, alpha); }"
  done
done

echo ""

# add vector

for prec in double float; do
  for arg1 in tensor::tensor_Dense\<$prec\> view_tensor_Dense\<vector\<$prec\>,$prec\> view_tensor_Dense\<matrix::Dense\<$prec\>,$prec\> view_tensor_Dense\<tensor::tensor_Dense\<$prec\>,$prec\>; do
    for arg2 in vector\<$prec\> view1D\<vector\<$prec\>,$prec\> view1D\<matrix::Dense\<$prec\>,$prec\> view1D\<tensor::tensor_Dense\<$prec\>,$prec\>; do
      echo "template <> void monolish::$arg1::diag_add(const $arg2 &vec) { tensor_Dense_diag_add_core(*this, vec.size(), vec.begin()); }"
    done
  done
done


echo "}"
