cat ./vsin.cpp | sed -e 's/sin/sqrt/g' > vsqrt.cpp
cat ./vsin.cpp | sed -e 's/sin/sinh/g' > vsinh.cpp
cat ./vsin.cpp | sed -e 's/sin/asin/g' > vasin.cpp
cat ./vsin.cpp | sed -e 's/sin/asinh/g' > vasinh.cpp
cat ./vsin.cpp | sed -e 's/sin/tan/g' > vtan.cpp
cat ./vsin.cpp | sed -e 's/sin/tanh/g' > vtanh.cpp
cat ./vsin.cpp | sed -e 's/sin/atan/g' > vatan.cpp
cat ./vsin.cpp | sed -e 's/sin/asin/g' > vasin.cpp
cat ./vsin.cpp | sed -e 's/sin/ceil/g' > vceil.cpp
cat ./vsin.cpp | sed -e 's/sin/floor/g' > vfloor.cpp
cat ./vsin.cpp | sed -e 's/sin/sign/g' > vsign.cpp
cat ./vsin.cpp | sed -e 's/sin/reciprocal/g' > vreciprocal.cpp

cat ./msin.cpp | sed -e 's/sin/sqrt/g' > msqrt.cpp
cat ./msin.cpp | sed -e 's/sin/sinh/g' > msinh.cpp
cat ./msin.cpp | sed -e 's/sin/asin/g' > masin.cpp
cat ./msin.cpp | sed -e 's/sin/asinh/g' > masinh.cpp
cat ./msin.cpp | sed -e 's/sin/tan/g' > mtan.cpp
cat ./msin.cpp | sed -e 's/sin/tanh/g' > mtanh.cpp
cat ./msin.cpp | sed -e 's/sin/atan/g' > matan.cpp
cat ./msin.cpp | sed -e 's/sin/asin/g' > masin.cpp
cat ./msin.cpp | sed -e 's/sin/ceil/g' > mceil.cpp
cat ./msin.cpp | sed -e 's/sin/floor/g' > mfloor.cpp
cat ./msin.cpp | sed -e 's/sin/sign/g' > msign.cpp
cat ./msin.cpp | sed -e 's/sin/reciprocal/g' > mreciprocal.cpp
