monolish_DIR?=$(HOME)/lib/monolish

CXX=g++
CXXFLAGS=-O3 -lm -std=c++11 -I $(monolish_DIR)/include/ -L$(monolish_DIR)/lib/ -lmonolish_cpu

OBJS=$(FUNC)_$(ARCH).out

all:$(OBJS)

$(FUNC)_$(ARCH).out: $(FUNC).cpp
	$(CXX) $(CXXFLAGS) $(LIBS) $^ -o $@
